Repository Development-team-1/just-pickup, pull requests merged in 2022-03, with the labels that each got.

#26 점주 로그인, axios interceptor, vue router, JWT 인증, access token url mapping
  owner-apigateway-service/src/main/java/com/justpickup/ownerapigatewayservice/OwnerApigatewayServiceApplication.java
  owner-apigateway-service/src/main/java/com/justpickup/ownerapigatewayservice/filter/AuthorizationHeaderFilter.java
  owner-apigateway-service/src/main/java/com/justpickup/ownerapigatewayservice/handler/GlobalExceptionHandler.java
  owner-apigateway-service/src/main/java/com/justpickup/ownerapigatewayservice/security/JwtTokenProvider.java
  owner-apigateway-service/src/main/resources/application.yml
  owner-vue/src/api/auth.js
  owner-vue/src/api/user.js
  owner-vue/src/common/jwt.js
  owner-vue/src/main.js
  owner-vue/src/router/index.js
  owner-vue/src/views/LoginUser.vue
  user-service/src/main/java/com/justpickup/userservice/domain/jwt/exception/AccessTokenNotValidException.java
  user-service/src/main/java/com/justpickup/userservice/domain/jwt/service/AccessTokenService.java
  user-service/src/main/java/com/justpickup/userservice/domain/jwt/service/AccessTokenServiceImpl.java
  user-service/src/main/java/com/justpickup/userservice/domain/jwt/service/RefreshTokenServiceImpl.java
  user-service/src/main/java/com/justpickup/userservice/domain/jwt/web/AuthController.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/dto/JwtTokenDto.java
  user-service/src/main/java/com/justpickup/userservice/global/exception/GlobalExceptionHandler.java
  user-service/src/main/java/com/justpickup/userservice/global/security/LoginAuthenticationFilter.java
  user-service/src/main/java/com/justpickup/userservice/global/utils/JwtTokenProvider.java
Labels: ✨ Feature, 🥰 Accessibility, 📬 API

#28 메뉴 등록
  owner-apigateway-service/src/main/java/com/justpickup/ownerapigatewayservice/filter/GlobalFilter.java
  owner-apigateway-service/src/main/resources/application.yml
  owner-vue/.env
  owner-vue/src/api/store.js
  owner-vue/src/main.js
  owner-vue/src/util/customUtil.js
  owner-vue/src/views/Category.vue
  owner-vue/src/views/ItemOption.vue
  owner-vue/src/views/Menu.vue
  owner-vue/src/views/MenuItem.vue
  store-service/src/main/java/com/justpickup/storeservice/domain/category/dto/CategoryDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/repository/CategoryRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/service/CategoryService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/dto/ItemDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/entity/Item.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/repository/ItemRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/web/ItemController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/dto/ItemOptionDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/entity/ItemOption.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/repository/ItemOptionRepository.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/repository/ItemOptionRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/service/ItemOptionService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/web/ItemOptionController.java
  store-service/src/main/java/com/justpickup/storeservice/global/dto/Result.java
  store-service/src/test/java/com/justpickup/storeservice/domain/item/web/ItemControllerTest.java
Labels: ✨ Feature, 📬 API, 🐞 BugFix

#27 고객 페이지 vue 프로젝트 생성 및 설정
  customer-vue/README.md
  customer-vue/babel.config.js
  customer-vue/jsconfig.json
  customer-vue/package.json
  customer-vue/public/_manifest.json
  customer-vue/public/app/icons/favicon.ico
  customer-vue/public/app/icons/icon-128x128.png
  customer-vue/public/app/icons/icon-144x144.png
  customer-vue/public/app/icons/icon-152x152.png
  customer-vue/public/app/icons/icon-192x192.png
  customer-vue/public/app/icons/icon-384x384.png
  customer-vue/public/app/icons/icon-512x512.png
  customer-vue/public/app/icons/icon-72x72.png
  customer-vue/public/app/icons/icon-96x96.png
  customer-vue/public/app/splash/iphoneplus.png
  customer-vue/public/app/splash/iphoneregular.png
  customer-vue/public/app/splash/iphonexr.png
  customer-vue/public/app/splash/iphonexs.png
  customer-vue/public/app/splash/iphonexsmax.png
  customer-vue/public/favicon.ico
  customer-vue/public/index.html
  customer-vue/public/styles/highlights/highlight_aqua.css
  customer-vue/public/styles/highlights/highlight_blue.css
  customer-vue/public/styles/highlights/highlight_brown.css
  customer-vue/public/styles/highlights/highlight_dark.css
  customer-vue/public/styles/highlights/highlight_grass.css
  customer-vue/public/styles/highlights/highlight_green.css
  customer-vue/public/styles/highlights/highlight_magenta.css
  customer-vue/public/styles/highlights/highlight_mint.css
  customer-vue/public/styles/highlights/highlight_night.css
  customer-vue/public/styles/highlights/highlight_orange.css
  customer-vue/public/styles/highlights/highlight_pink2.css
  customer-vue/public/styles/highlights/highlight_red.css
  customer-vue/public/styles/highlights/highlight_sunny.css
  customer-vue/public/styles/highlights/highlight_teal.css
  customer-vue/public/styles/highlights/highlight_yellow.css
  customer-vue/src/App.vue
  customer-vue/src/assets/logo.png
  customer-vue/src/components/HelloWorld.vue
  customer-vue/src/main.js
  customer-vue/src/router/router.js
  customer-vue/src/views/Layout/FooterBar.vue
  customer-vue/src/views/Layout/HomeLayout.vue
  customer-vue/src/views/Layout/TopBar.vue
  customer-vue/src/views/TestView.vue
  customer-vue/vue.config.js
Labels: ✨ Feature

#29 feat(user-service): Oauth 사용자 JWT
  customer-vue/vue.config.js
  user-service/src/main/java/com/justpickup/userservice/domain/jwt/service/OAuthService.java
  user-service/src/main/java/com/justpickup/userservice/global/security/SecurityConfig.java
Labels: ✨ Feature

#30 feat(customer-vue): 고객 프로젝트 생성
  customer-vue/README.md
  customer-vue/babel.config.js
  customer-vue/jsconfig.json
  customer-vue/package.json
  customer-vue/public/favicon.ico
  customer-vue/public/index.html
  customer-vue/src/App.vue
  customer-vue/src/assets/logo.png
  customer-vue/src/components/HelloWorld.vue
  customer-vue/src/main.js
  customer-vue/src/plugins/vuetify.js
  customer-vue/src/router/router.js
  customer-vue/src/views/HomeView.vue
  customer-vue/src/views/Layout/AppNavigation.vue
  customer-vue/src/views/Layout/BottomNavigation.vue
  customer-vue/src/views/Layout/HomeLayout.vue
  customer-vue/vue.config.js
Labels: ⚙ Setting, 🐞 BugFix

#31 Refactor feature
  owner-apigateway-service/src/main/java/com/justpickup/ownerapigatewayservice/handler/GlobalExceptionHandler.java
  owner-apigateway-service/src/main/resources/application.yml
  owner-vue/src/api/store.js
  owner-vue/src/components/ItemOption.vue
  owner-vue/src/components/MenuItem.vue
  owner-vue/src/main.js
  owner-vue/src/util/customUtil.js
  owner-vue/src/views/Menu.vue
  store-service/src/main/java/com/justpickup/storeservice/domain/category/entity/Category.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/web/CategoryController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/web/ItemController.java
  user-service/src/main/java/com/justpickup/userservice/UserServiceApplication.java
Labels: 🐞 BugFix, 🔨 Refactor

#33 Just-Pickup 매장 검색 페이지 및 로직 구현
  customer-vue/package.json
  customer-vue/src/api/store.js
  customer-vue/src/router/router.js
  customer-vue/src/views/Layout/HomeLayout.vue
  customer-vue/src/views/SearchStore.vue
  store-service/src/docs/asciidoc/api-docs.adoc
  store-service/src/main/java/com/justpickup/storeservice/StoreServiceApplication.java
  store-service/src/main/java/com/justpickup/storeservice/domain/map/entity/Map.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/dto/SearchStoreCondition.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/dto/SearchStoreResult.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/entity/Store.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/repository/StoreRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreController.java
  store-service/src/test/java/com/justpickup/storeservice/domain/store/web/StoreControllerTest.java
Labels: ✨ Feature

#34 feat(customer vue, customer-gateway-service): SSL 적용
  customer-apigateway-service/src/main/resources/application.yml
  customer-apigateway-service/src/main/resources/baeldung.p12
  customer-vue/.env
  customer-vue/mydomain.key
  customer-vue/src/api/store.js
  customer-vue/src/main.js
  customer-vue/trustService.cer
  customer-vue/vue.config.js
  user-service/src/main/java/com/justpickup/userservice/domain/jwt/service/OAuthService.java
Labels: 🐞 BugFix

#35 고객 검색 - 즐겨찾기 개수
  customer-vue/src/views/SearchStore.vue
  store-service/src/main/java/com/justpickup/storeservice/domain/favoritestore/repository/FavoriteStoreCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/dto/SearchStoreResult.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreController.java
  store-service/src/test/java/com/justpickup/storeservice/domain/store/web/StoreControllerTest.java
Labels: ✨ Feature

#38 리팩토링 컨트롤러 분리 (주문, 지난주문, JWT)
  customer-vue/.env
  customer-vue/src/api/store.js
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderController.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderOwnerApiControllerTest.java
  owner-apigateway-service/src/main/java/com/justpickup/ownerapigatewayservice/filter/AuthorizationHeaderFilter.java
  owner-apigateway-service/src/main/resources/application.yml
  owner-vue/.env
  owner-vue/package.json
  owner-vue/src/api/auth.js
  owner-vue/src/api/order.js
  owner-vue/src/api/user.js
  owner-vue/src/main.js
  owner-vue/src/views/LoginUser.vue
  owner-vue/vue.config.js
  store-service/src/docs/asciidoc/api-docs.adoc
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreCustomerApiController.java
  store-service/src/test/java/com/justpickup/storeservice/domain/store/web/StoreCustomerApiControllerTest.java
Labels: 🔨 Refactor

#39 즐겨찾기
  customer-apigateway-service/src/main/java/com/justpickup/customerapigatewayservice/CustomerApigatewayServiceApplication.java
  customer-vue/src/api/store.js
  customer-vue/src/components/SlideStore.vue
  customer-vue/src/router/router.js
  customer-vue/src/views/HomeView.vue
  customer-vue/src/views/LoginPage.vue
  owner-vue/src/api/store.js
  owner-vue/src/views/Category.vue
  owner-vue/src/views/Menu.vue
  owner-vue/vue.config.js
  store-service/src/docs/asciidoc/api-docs.adoc
  store-service/src/main/java/com/justpickup/storeservice/StoreServiceApplication.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/dto/CategoryDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/web/CategoryOwnerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/favoritestore/entity/FavoriteStore.java
  store-service/src/main/java/com/justpickup/storeservice/domain/favoritestore/repository/FavoriteStoreRepository.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/entity/Store.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/repository/StoreRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreCustomerApiController.java
  store-service/src/test/java/com/justpickup/storeservice/domain/category/web/CategoryOwnerApiControllerTest.java
  store-service/src/test/java/com/justpickup/storeservice/domain/store/web/StoreCustomerApiControllerTest.java
Labels: ✨ Feature, 📬 API

#40 [Just Pick-up] 주문내역
  customer-apigateway-service/src/main/resources/application.yml
  customer-vue/.env
  customer-vue/src/api/order.js
  customer-vue/src/components/BottomNavigation.vue
  customer-vue/src/components/OrderHistoryCard.vue
  customer-vue/src/main.js
  customer-vue/src/router/router.js
  customer-vue/src/views/OrderHistory.vue
  order-service/src/docs/asciidoc/api-docs.adoc
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/OrderDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/repository/OrderRepositoryCustom.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderService.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderServiceImpl.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiController.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderOwnerApiController.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiControllerTest.java
Labels: ✨ Feature

#41 고객 홈 가까이있는매장
  customer-vue/src/api/store.js
  customer-vue/src/assets/just-logo.png
  customer-vue/src/assets/store.jpeg
  customer-vue/src/components/AppNavigation.vue
  customer-vue/src/components/OrderHistoryCard.vue
  customer-vue/src/components/SlideStore.vue
  customer-vue/src/views/HomeView.vue
  customer-vue/src/views/SearchStore.vue
Labels: ✨ Feature, 🎨 Html&css

#42 Refactor item
  owner-vue/src/api/store.js
  store-service/src/docs/asciidoc/api-docs.adoc
  store-service/src/main/java/com/justpickup/storeservice/domain/category/web/CategoryOwnerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/web/ItemController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/web/ItemOwnerApiController.java
  store-service/src/test/java/com/justpickup/storeservice/domain/category/web/CategoryOwnerApiControllerTest.java
  store-service/src/test/java/com/justpickup/storeservice/domain/item/web/ItemControllerTest.java
  store-service/src/test/java/com/justpickup/storeservice/domain/item/web/ItemOwnerApiControllerTest.java
  store-service/src/test/java/com/justpickup/storeservice/domain/store/web/StoreCustomerApiControllerTest.java
Labels: 📃 Docs, 🔨 Refactor

#43 feat(customer-vue): 즐겨찾기 페이지 추가
  customer-vue/src/components/BottomNavigation.vue
  customer-vue/src/components/SlideStore.vue
  customer-vue/src/router/router.js
  customer-vue/src/views/FavoriteStore.vue
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreCustomerApiController.java
Labels: ✨ Feature

#44 고객 상품 페이지
  customer-vue/src/api/store.js
  customer-vue/src/components/StoreNavigation.vue
  customer-vue/src/router/router.js
  customer-vue/src/views/Layout/StoreLayout.vue
  customer-vue/src/views/SearchStore.vue
  customer-vue/src/views/StoreView.vue
  store-service/src/docs/asciidoc/api-docs.adoc
  store-service/src/main/java/com/justpickup/storeservice/StoreServiceApplication.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/entity/Category.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/service/CategoryService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/web/CategoryCustomerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/web/CategoryOwnerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/dto/ItemDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/entity/Item.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/repository/ItemRepository.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/web/ItemOwnerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/dto/ItemOptionDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/entity/ItemOption.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/repository/ItemOptionRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/dto/StoreDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/entity/Store.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/exception/NotExistStoreException.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/repository/StoreRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreController.java
  store-service/src/main/java/com/justpickup/storeservice/global/SqlCommandLineRunner.java
  store-service/src/test/java/com/justpickup/storeservice/domain/category/web/CategoryOwnerApiControllerTest.java
  store-service/src/test/java/com/justpickup/storeservice/domain/item/web/ItemOwnerApiControllerTest.java
  store-service/src/test/java/com/justpickup/storeservice/domain/store/web/StoreControllerTest.java
  store-service/src/test/java/com/justpickup/storeservice/domain/store/web/StoreCustomerApiControllerTest.java
Labels: ✨ Feature

#45 [Just Pickup] 알림 서비스 구현
  customer-apigateway-service/src/main/java/com/justpickup/customerapigatewayservice/handler/GlobalExceptionHandler.java
  customer-apigateway-service/src/main/resources/application.yml
  customer-vue/src/api/notification.js
  customer-vue/src/components/AppNavigation.vue
  customer-vue/src/router/router.js
  customer-vue/src/views/Layout/HomeLayout.vue
  customer-vue/src/views/NotificationView.vue
  notification-service/build.gradle
  notification-service/src/docs/asciidoc/api-docs.adoc
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/dto/FindNotificationDto.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/dto/UpdateNotificationDto.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/entity/Notification.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/exception/NotExistNotification.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/repository/NotificationRepository.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/service/NotificationService.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/service/NotificationServiceImpl.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/web/NotificationApiController.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/web/NotificationController.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/SqlCommandLineRunner.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/dto/Code.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/dto/Result.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/dto/Yn.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/entity/BaseEntity.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/exception/CustomException.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/exception/GlobalExceptionHandler.java
  notification-service/src/test/java/com/justpickup/notificationservice/config/TestConfig.java
  notification-service/src/test/java/com/justpickup/notificationservice/domain/notification/web/NotificationApiControllerTest.java
  notification-service/src/test/java/com/justpickup/notificationservice/domain/notification/web/NotificationControllerTest.java
Labels: ✨ Feature, 📬 API

#46 상품상세 주문하기
  customer-vue/src/api/order.js
  customer-vue/src/api/store.js
  customer-vue/src/components/AppNavigation.vue
  customer-vue/src/router/router.js
  customer-vue/src/views/HomeView.vue
  customer-vue/src/views/ItemDetail.vue
  customer-vue/src/views/OrderPage.vue
  order-service/build.gradle
  order-service/src/docs/asciidoc/api-docs.adoc
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/FetchOrderDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/OrderDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/entity/Order.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/exception/OrderException.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/repository/OrderRepository.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/repository/OrderRepositoryCustom.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderSender.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderService.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderServiceImpl.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiController.java
  order-service/src/main/java/com/justpickup/orderservice/domain/orderItem/dto/OrderItemDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/orderItem/entity/OrderItem.java
  order-service/src/main/java/com/justpickup/orderservice/domain/orderItemOption/dto/OrderItemOptionDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/orderItemOption/entity/OrderItemOption.java
  order-service/src/main/java/com/justpickup/orderservice/domain/orderItemOption/repository/OrderItemOptionRepository.java
  order-service/src/main/java/com/justpickup/orderservice/global/config/KafkaConfig.java
  order-service/src/main/resources/application.yml
  order-service/src/test/java/com/justpickup/orderservice/domain/order/service/OrderSenderTest.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiControllerTest.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/dto/FetchItemDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/repository/ItemRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/web/ItemCustomerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/web/ItemOwnerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/dto/StoreDto.java
  store-service/src/main/resources/application.yml
  store-service/src/test/java/com/justpickup/storeservice/domain/item/web/ItemOwnerApiControllerTest.java
  user-service/src/main/java/com/justpickup/userservice/UserServiceApplication.java
Labels: ✨ Feature, 📬 API, 📃 Docs, ✅ Test

#47 [점주] 주문 상태변경
  order-service/src/docs/asciidoc/api-docs.adoc
  order-service/src/main/java/com/justpickup/orderservice/OrderServiceApplication.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/OrderMainDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/OrderMainResult.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/entity/Order.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/entity/OrderListener.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/entity/OrderStatus.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/repository/OrderRepositoryCustom.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderService.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderServiceImpl.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderController.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderOwnerApiController.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderControllerTest.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderOwnerApiControllerTest.java
  owner-vue/src/api/order.js
  owner-vue/src/components/OrderCard.vue
  owner-vue/src/views/Order.vue
Labels: ✨ Feature

#48 refactor(services): 개발 , 운영 설정 분리
  customer-apigateway-service/build.gradle
  customer-apigateway-service/src/main/resources/application.yml
  notification-service/build.gradle
  notification-service/src/main/resources/application.yml
  order-service/build.gradle
  order-service/src/main/resources/application.yml
  owner-apigateway-service/build.gradle
  owner-apigateway-service/src/main/resources/application.yml
  store-service/build.gradle
  store-service/src/main/resources/application.yml
Labels: 🌏 Deploy

#50 Order feign
  customer-apigateway-service/src/main/resources/application.yml
  customer-vue/src/main.js
  customer-vue/src/router/router.js
  customer-vue/src/views/ItemDetail.vue
  customer-vue/src/views/Layout/StoreLayout.vue
  customer-vue/src/views/LoginPage.vue
  customer-vue/src/views/OrderPage.vue
  notification-service/src/main/resources/application.yml
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/FetchOrderDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/entity/Order.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/entity/OrderListener.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderSender.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderService.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderServiceImpl.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiController.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/GetItemResponse.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/GetStoreReseponse.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/OptionType.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/StoreClient.java
  order-service/src/main/java/com/justpickup/orderservice/global/config/KafkaConfig.java
  order-service/src/main/resources/application.yml
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiControllerTest.java
  owner-apigateway-service/src/main/resources/application.yml
  owner-vue/src/api/store.js
  store-service/src/docs/asciidoc/api-docs.adoc
  store-service/src/main/java/com/justpickup/storeservice/domain/item/dto/GetItemDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/repository/ItemRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/web/ItemCustomerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/global/SqlCommandLineRunner.java
  store-service/src/main/resources/application.yml
  store-service/src/main/resources/data/data.sql
  store-service/src/test/java/com/justpickup/storeservice/domain/item/web/ItemCustomerApiControllerTest.java
  user-service/src/main/resources/application.yml
Labels: ✨ Feature, 📬 API

#51 Mypage
  customer-vue/src/api/user.js
  customer-vue/src/components/BottomNavigation.vue
  customer-vue/src/views/MyPage.vue
  user-service/src/docs/asciidoc/api-docs.adoc
  user-service/src/main/java/com/justpickup/userservice/domain/user/dto/UserDto.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/web/UserController.java
  user-service/src/test/java/com/justpickup/userservice/domain/user/web/UserControllerTest.java
Labels: ✨ Feature, 📬 API

#52 점주 주문내역, Just Pickup 주문내역 관련 Feign 클라이언트 로직 추가
  customer-vue/src/views/OrderHistory.vue
  order-service/src/docs/asciidoc/api-docs.adoc
  order-service/src/main/java/com/justpickup/orderservice/OrderServiceApplication.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/OrderHistoryDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/OrderMainDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/PrevOrderDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/entity/Order.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/repository/OrderRepositoryCustom.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderService.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderServiceImpl.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderController.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiController.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderOwnerApiController.java
  order-service/src/main/java/com/justpickup/orderservice/domain/orderItem/entity/OrderItem.java
  order-service/src/main/java/com/justpickup/orderservice/global/SqlCommandLineRunner.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/GetItemsResponse.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/GetStoreResponse.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/StoreByUserIdResponse.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/StoreClient.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/user/UserClient.java
  order-service/src/main/resources/static/docs/api-docs.html
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderControllerTest.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiControllerTest.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderOwnerApiControllerTest.java
  owner-apigateway-service/src/main/resources/application.yml
  owner-vue/src/components/OrderCard.vue
  owner-vue/src/views/PrevOrder.vue
  store-service/src/docs/asciidoc/api-docs.adoc
  store-service/src/main/java/com/justpickup/storeservice/domain/item/dto/ItemsDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/web/ItemController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/web/ItemOwnerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/entity/ItemOption.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/dto/StoreByUserIdDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/dto/StoreDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreOwnerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/global/SqlCommandLineRunner.java
  store-service/src/main/java/com/justpickup/storeservice/global/client/user/UserClient.java
  store-service/src/main/resources/application.yml
  store-service/src/main/resources/static/docs/api-docs.html
  store-service/src/test/java/com/justpickup/storeservice/domain/item/web/ItemControllerTest.java
  store-service/src/test/java/com/justpickup/storeservice/domain/item/web/ItemOwnerApiControllerTest.java
  store-service/src/test/java/com/justpickup/storeservice/domain/store/web/StoreControllerTest.java
  store-service/src/test/java/com/justpickup/storeservice/domain/store/web/StoreOwnerApiControllerTest.java
  user-service/src/docs/asciidoc/api-docs.adoc
  user-service/src/main/java/com/justpickup/userservice/UserServiceApplication.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/repository/StoreOwnerRepository.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/service/UserService.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/service/UserServiceImpl.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/web/UserController.java
  user-service/src/main/java/com/justpickup/userservice/global/SqlCommandLineRunner.java
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/justpickup/userservice/domain/user/web/UserControllerTest.java
Labels: ✨ Feature, 📬 API, ✅ Test

#53 알림 주문신청 (카프카 컨슈머, 페인클라이언트)
  notification-service/build.gradle
  notification-service/src/main/java/com/justpickup/notificationservice/NotificationServiceApplication.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/messagequeue/NotificationConsumer.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/messagequeue/OrderStatus.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/service/NotificationService.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/service/NotificationServiceImpl.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/client/store/GetStoreResponse.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/client/store/StoreClient.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/config/FeignClientConfig.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/config/KafkaConsumerConfig.java
  notification-service/src/main/java/com/justpickup/notificationservice/global/entity/BaseEntity.java
  notification-service/src/test/java/com/justpickup/notificationservice/domain/notification/messagequeue/NotificationConsumerTest.java
  notification-service/src/test/java/com/justpickup/notificationservice/domain/notification/web/NotificationControllerTest.java
Labels: ✨ Feature

#55 중요 버그 수정
  customer-vue/src/api/auth.js
  customer-vue/src/api/store.js
  customer-vue/src/common/jwt.js
  customer-vue/src/components/AppNavigation.vue
  customer-vue/src/components/StoreNavigation.vue
  customer-vue/src/router/router.js
  customer-vue/src/views/ItemDetail.vue
  customer-vue/src/views/LoginPage.vue
  customer-vue/src/views/OrderPage.vue
  customer-vue/src/views/StoreView.vue
  owner-vue/src/api/store.js
  owner-vue/src/components/MenuItem.vue
  owner-vue/src/views/Layout/DashboardLayout.vue
  owner-vue/src/views/Layout/Sidebar.vue
  store-service/src/docs/asciidoc/api-docs.adoc
  store-service/src/main/java/com/justpickup/storeservice/domain/favoritestore/dto/GetFavoriteStoreByStoreIdDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/favoritestore/repository/FavoriteStoreRepository.java
  store-service/src/main/java/com/justpickup/storeservice/domain/favoritestore/service/FavoriteStoreService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/favoritestore/web/FavoriteStoreCustomerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/repository/ItemRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemServiceImpl.java
  store-service/src/test/java/com/justpickup/storeservice/domain/favoritestore/web/FavoriteStoreCustomerApiControllerTest.java
  user-service/src/main/java/com/justpickup/userservice/domain/jwt/service/OAuthService.java
Labels: ✨ Feature, 🐞 BugFix, 📃 Docs, 🔨 Refactor

#54 버그픽스 상범
  customer-vue/src/components/OrderHistoryCard.vue
  customer-vue/src/components/SlideStore.vue
  customer-vue/src/router/router.js
  customer-vue/src/views/FavoriteStore.vue
  customer-vue/src/views/OrderHistory.vue
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/OrderHistoryDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/repository/OrderRepositoryCustom.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderServiceImpl.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderController.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiController.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/GetStoreReseponse.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/StoreClient.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/user/UserClient.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiControllerTest.java
  owner-apigateway-service/src/main/java/com/justpickup/ownerapigatewayservice/filter/AuthorizationHeaderFilter.java
  owner-apigateway-service/src/main/resources/application.yml
  owner-vue/.env
  owner-vue/src/api/auth.js
  owner-vue/src/api/notification.js
  owner-vue/src/api/store.js
  owner-vue/src/api/user.js
  owner-vue/src/common/jwt.js
  owner-vue/src/components/ItemOption.vue
  owner-vue/src/components/MenuItem.vue
  owner-vue/src/components/OrderCard.vue
  owner-vue/src/main.js
  owner-vue/src/router/index.js
  owner-vue/src/views/Layout/DashboardLayout.vue
  owner-vue/src/views/Layout/Topbar.vue
  owner-vue/src/views/LoginUser.vue
  owner-vue/src/views/Menu.vue
  owner-vue/src/views/NotificationView.vue
  owner-vue/src/views/Order.vue
  owner-vue/src/views/PrevOrder.vue
  owner-vue/vue.config.js
  store-service/src/main/generated/com/justpickup/storeservice/domain/category/entity/QCategory.java
  store-service/src/main/generated/com/justpickup/storeservice/domain/favoritestore/entity/QFavoriteStore.java
  store-service/src/main/generated/com/justpickup/storeservice/domain/item/entity/QItem.java
  store-service/src/main/generated/com/justpickup/storeservice/domain/itemoption/entity/QItemOption.java
  store-service/src/main/generated/com/justpickup/storeservice/domain/map/entity/QMap.java
  store-service/src/main/generated/com/justpickup/storeservice/domain/review/entity/QReview.java
  store-service/src/main/generated/com/justpickup/storeservice/domain/reviewreply/entity/QReviewReply.java
  store-service/src/main/generated/com/justpickup/storeservice/domain/store/entity/QStore.java
  store-service/src/main/generated/com/justpickup/storeservice/global/entity/QAddress.java
  store-service/src/main/generated/com/justpickup/storeservice/global/entity/QBaseEntity.java
  store-service/src/main/generated/com/justpickup/storeservice/global/entity/QPhoto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/repository/CategoryRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/service/CategoryService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/web/CategoryCustomerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/category/web/CategoryOwnerApiController.java
  user-service/src/main/java/com/justpickup/userservice/domain/jwt/service/RefreshTokenServiceImpl.java
  user-service/src/main/java/com/justpickup/userservice/domain/jwt/web/AuthController.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/dto/CustomerDto.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/dto/StoreOwnerDto.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/dto/UserDto.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/service/UserService.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/service/UserServiceImpl.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/web/UserController.java
  user-service/src/main/java/com/justpickup/userservice/global/utils/CookieProvider.java
Labels: 🐞 BugFix

#56 점주 매장등록
  owner-apigateway-service/src/main/resources/application.yml
  owner-vue/package.json
  owner-vue/src/api/user.js
  owner-vue/src/main.js
  owner-vue/src/views/RegisterUser.vue
  store-service/src/docs/asciidoc/api-docs.adoc
  store-service/src/main/java/com/justpickup/storeservice/domain/store/dto/PostStoreDto.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/entity/Store.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/service/StoreServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreController.java
  store-service/src/main/java/com/justpickup/storeservice/domain/store/web/StoreOwnerApiController.java
  store-service/src/main/java/com/justpickup/storeservice/global/SqlCommandLineRunner.java
  store-service/src/main/java/com/justpickup/storeservice/global/entity/Address.java
  store-service/src/test/java/com/justpickup/storeservice/domain/store/web/StoreOwnerApiControllerTest.java
  user-service/src/docs/asciidoc/api-docs.adoc
  user-service/src/main/java/com/justpickup/userservice/UserServiceApplication.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/dto/PostOwnerDto.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/dto/PostStoreDto.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/entity/User.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/service/UserService.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/service/UserServiceImpl.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/web/UserController.java
  user-service/src/main/java/com/justpickup/userservice/domain/user/web/UserOwnerApiController.java
  user-service/src/main/java/com/justpickup/userservice/global/client/exception/FeignClientException.java
  user-service/src/main/java/com/justpickup/userservice/global/client/exception/FeignClientExceptionErrorDecoder.java
  user-service/src/main/java/com/justpickup/userservice/global/client/store/PostStoreRequest.java
  user-service/src/main/java/com/justpickup/userservice/global/client/store/StoreClient.java
  user-service/src/main/java/com/justpickup/userservice/global/config/FeignClientConfig.java
  user-service/src/main/java/com/justpickup/userservice/global/exception/GlobalExceptionHandler.java
  user-service/src/main/java/com/justpickup/userservice/global/security/SecurityConfig.java
  user-service/src/test/java/com/justpickup/userservice/domain/user/web/UserControllerTest.java
  user-service/src/test/java/com/justpickup/userservice/domain/user/web/UserOwnerApiControllerTest.java
Labels: ✨ Feature

#57 주문내역 상세보기
  customer-vue/src/api/order.js
  customer-vue/src/components/OrderHistoryCard.vue
  customer-vue/src/main.js
  customer-vue/src/router/router.js
  customer-vue/src/views/OrderDetail.vue
  customer-vue/src/views/OrderHistory.vue
  order-service/src/docs/asciidoc/api-docs.adoc
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/OrderDetailDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/entity/Order.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/repository/OrderRepositoryCustom.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderService.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderServiceImpl.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderController.java
  order-service/src/main/java/com/justpickup/orderservice/domain/orderItem/repository/OrderItemRepositoryCustom.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/GetItemResponse.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/ItemOptionsResponse.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/StoreClient.java
  order-service/src/main/java/com/justpickup/orderservice/global/exception/GlobalExceptionHandler.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderControllerTest.java
  owner-vue/src/api/order.js
  owner-vue/src/components/OrderCard.vue
  owner-vue/src/components/OrderDetailDialog.vue
  owner-vue/src/main.js
  owner-vue/src/views/PrevOrder.vue
  store-service/src/main/java/com/justpickup/storeservice/domain/item/repository/ItemRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/repository/ItemOptionRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/service/ItemOptionService.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/service/ItemOptionServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/web/ItemOptionController.java
Labels: ✨ Feature

#58 Owner dashboard
  customer-vue/src/api/order.js
  customer-vue/src/components/AppNavigation.vue
  customer-vue/src/components/StoreNavigation.vue
  customer-vue/src/router/router.js
  customer-vue/src/views/ItemDetail.vue
  customer-vue/src/views/Layout/StoreLayout.vue
  customer-vue/src/views/MyPage.vue
  customer-vue/src/views/OrderPage.vue
  customer-vue/src/views/StoreView.vue
  order-service/src/docs/asciidoc/api-docs.adoc
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/DashBoardDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/dto/FetchOrderDto.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/entity/Order.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/repository/OrderRepository.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/repository/OrderRepositoryCustom.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderService.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderServiceImpl.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/web/OrderOwnerApiController.java
  order-service/src/main/java/com/justpickup/orderservice/domain/orderItem/service/OrderItemService.java
  order-service/src/main/java/com/justpickup/orderservice/domain/orderItem/web/OrderItemCustomerApiController.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderCustomerApiControllerTest.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderOwnerApiControllerTest.java
  order-service/src/test/java/com/justpickup/orderservice/domain/orderItem/web/OrderItemCustomerApiControllerTest.java
  owner-vue/package.json
  owner-vue/src/api/order.js
  owner-vue/src/components/ItemOption.vue
  owner-vue/src/components/MenuItem.vue
  owner-vue/src/js/CustomChart.js
  owner-vue/src/router/index.js
  owner-vue/src/views/HomeDashBoard.vue
  owner-vue/src/views/Layout/DashboardLayout.vue
  owner-vue/src/views/Layout/Sidebar.vue
  owner-vue/src/views/Layout/Topbar.vue
  owner-vue/src/views/LoginUser.vue
  owner-vue/src/views/Menu.vue
  store-service/src/main/java/com/justpickup/storeservice/domain/item/repository/ItemRepositoryCustom.java
  store-service/src/main/java/com/justpickup/storeservice/domain/item/service/ItemServiceImpl.java
  store-service/src/main/java/com/justpickup/storeservice/domain/itemoption/repository/ItemOptionRepository.java
Labels: ✨ Feature, 📬 API, 🐞 BugFix

#59 feat(order, notification, kafka): 주문 상태 변경 시 kafka 메시지 발송
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/messagequeue/NotificationConsumer.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/service/NotificationService.java
  notification-service/src/main/java/com/justpickup/notificationservice/domain/notification/service/NotificationServiceImpl.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/entity/OrderListener.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/repository/OrderRepositoryCustom.java
  order-service/src/main/java/com/justpickup/orderservice/domain/order/service/OrderSender.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/store/StoreClient.java
  order-service/src/main/java/com/justpickup/orderservice/global/client/user/UserClient.java
  order-service/src/test/java/com/justpickup/orderservice/domain/order/web/OrderControllerTest.java
Labels: ✨ Feature

#60 feat(zipkin): 모니터링 시스템 zipkin 추가
  customer-apigateway-service/build.gradle
  customer-apigateway-service/src/main/resources/application.yml
  notification-service/build.gradle
  notification-service/src/main/resources/application.yml
  order-service/build.gradle
  order-service/src/main/resources/application.yml
  owner-apigateway-service/build.gradle
  owner-apigateway-service/src/main/resources/application.yml
  store-service/build.gradle
  store-service/src/main/resources/application.yml
  user-service/build.gradle
  user-service/src/main/resources/application.yml
Labels: ✨ Feature, ⚙ Setting

#62 api gateway redis rate limiter 적용
  customer-apigateway-service/build.gradle
  customer-apigateway-service/src/main/java/com/justpickup/customerapigatewayservice/CustomerApigatewayServiceApplication.java
  customer-apigateway-service/src/main/resources/application.yml
  owner-apigateway-service/build.gradle
  owner-apigateway-service/src/main/java/com/justpickup/ownerapigatewayservice/OwnerApigatewayServiceApplication.java
  owner-apigateway-service/src/main/resources/application.yml
Labels: ✨ Feature, 📬 API
